### ISSUE TITLE
Invalid Biome ID crash

### ISSUE THREAD

**Issue by MokahTGS** [superfluke/enderoni#14]
Getting a crash with this mod: https://paste.dimdev.org/jucoyexaje.mccrash

Full mod list: https://paste.dimdev.org/uhomuwipur.md

Forge 2836
stygian-1.0.4

**Comment by superfluke** [comment]
`Invalid id 256 - maximum id range exceeded.`
You've simply got too many biomes in your pack, there's a limit of 256. Some mods try to remove this limit but they are kind of hit or miss in their effectiveness.

**Comment by MokahTGS** [comment]
Nope...played with way more biomes than this.  That's what Not Enough IDs is for.

**Comment by superfluke** [comment]
Notenoughids extends the block ID limit, not biomes. Maybe you're thinking of justenoughids (gotta love these names)
