### ISSUE TITLE
End has overworld biomes

### ISSUE THREAD

**Issue by ghost** [superfluke/enderoni#5]
The end now has overworld biomes:

![2018-10-28_17 53 13](https://user-images.githubusercontent.com/36042986/47622431-41b6eb80-dadb-11e8-83de-866a56571288.png)

I have the follow installed:
Biomes o Plenty
Traverse
Hexlands
Stygian End

**Comment by superfluke** [comment]
Ok, I've tried just about everything I can think of and cannot get the bug to show up for me. Tried SE with each of the other 3 mods individually and it all looked normal. Tried SE with all 3 mods combined on normal, BoP, hexlands, and BoP hexlands world types and all of them looked normal. Tried using Natures compass to find a forest biome in the end and still nada.

So I'll need more info here. Does this bug happen with only those 4 mods installed? What world type did you use? Are the overworld biomes rare, or is the entire end dim converted to overworld biomes?

**Comment by ghost** [comment]
I'll start separating mods in a testing instance and I'll report back as I get the information.

**Comment by ghost** [comment]
I can confirm that Stygian End did cause this bug, updated responses:

What world type did you use?:
Hexlands, BOP Hexlands, Vanilla, Quark "Realistic."

Are the overworld biomes rare, or is the entire end dim converted to overworld biomes:
The entire end is converted (yes the 1000+ block outskirt end islands with the end cities is also converted).

Does this bug happen with only those 4 mods installed? (UPDATED MOD LIST):
I compiled all the mods I has that deal with terrain generation and dimensions:

BiomesOPlenty-1.12.2-7.0.1.2399-universal
hexlands-1.8.1
AutoRegLib-1.3-20 (Quark Library)
RebornCore-1.12.2-3.10.2.337-universal (Simple Void World Library)
Optifine_1.12.2_HD_U_E2
QuarkOddities-1.12.2
Quark-r1.5-130
Simple-Void-World-1.12-1.2.0.9-universal
Traverse-1.12.2-1.6.0-69
ActuallyAdditions-1.12.2-r143
SimpleDimensions-MC1.12-1.3.1
somelikeitdry-1.1.0
worleycaves-1.3.0
twilightforest-1.12.2-3.8.689-universal
stygian-1.0.1

When I had Stygian End installed with this debug mod list (and my full mod list) the biomes were overworld like, when I removed Stygian end, the end generated normally in a new word.

(Also side note, I made a post a while ago about BOP biomes not generating when Traverse was installed even when I had the generator set to BOP Hexlands, that is still happening to me even in this condensed list of mods I put together for testing this original overworld end bug).

Finally ~ could the forge version have anything to do with this?
I am running forge: "1.12.2-forge1.12.2-14.23.4.2705"

**Comment by superfluke** [comment]
Think I've solved the issue. Was a bad interaction between Stygian End and Some Like It Dry. 

Also for your other issue about BoP biomes not generating with Traverse, I believe Some Like It Dry might be causing that as well. Some Like It Dry and BoP are not compatible, but I believe BoP has its own settings for reducing the number of oceans. Feel free to reopen or post a new issue if that issue still happens with SLID.
