### ISSUE TITLE
Trees don't grow?

### ISSUE THREAD

**Issue by PCSpinner** [superfluke/enderoni#7]
I'm trying to get Wyrmwood saplings to grow, but it doesn't seem to work.

I've tried on endstone and on stygian grass, with light and without, single saplings and groups up to 6x6. All of this in the end. I've tried bone meal and Project E's watch of flowing time to speed things up.

Do the saplings not grow or am I missing some esoteric growth requirement?

**Comment by superfluke** [comment]
Yeah now that I think about it, I believe I added the requirement of needing a endstone/grass under all the trunk blocks to keep the trees from hanging over the void in the end. 
Try making an 11x11 square of endstone/grass with a sapling in the middle and see if that works.

**Comment by PCSpinner** [comment]
I tried clearing out a 21x21 area, nothing above that could get in the way, with a solid endstone, solid stygian grass, and mixed floor and still no growth.

**Comment by superfluke** [comment]
Turned on logging to see what was keeping the sapling from growing

> Wyrmwood sapling blocked tree from spawning

:man_facepalming: should be fixed now. No need for a 11x11 area or anything. Even seems to grow on grass, but that's an issue for another day
