### ISSUE TITLE
[Feature] End BiomeDict/Biome Naming

### ISSUE THREAD

**Issue by drakray** [superfluke/enderoni#8]
Could it be possible to register your biome with the BiomeDict please?, for better cross-mod compat, specifically with OreSpawn
Also, OreSpawn REALLY do not like having space in biome name([it just plain crash](https://pastebin.com/rVeHWLWd)), I think it's even a Forge/Minecraft naming convention to use underscore, something to do with Java IIRC.
Anyway really nice work on this so far, can't wait to see your future plan unfold :D

**Comment by superfluke** [comment]
Ahh yeah I think I see what I did wrong there, I'll try and work that out when have a chance to sit down with it.
